### ISSUE TITLE
Update please?

### ISSUE THREAD

**Issue by sleekweasel** [serandel/kscript-docker#1]
I was having problems with the @file:DependsOn style annotations complaining with

```
[kscript] Resolving dependencies...
[kscript]     Resolving de.mpicbg.scicomp:kutils:0.4...[kscript] [ERROR] Failed to lookup dependencies. Check dependency locators or file a bug on https://github.com/holgerbrandl/kscript
[kscript] [ERROR] Exception: org.sonatype.aether.resolution.DependencyResolutionException: failed to load 'de.mpicbg.scicomp:kutils:jar:0.4 (compile)' from ["jcenter (http://jcenter.bintray.com/, releases+snapshots) without authentication"] into /root/.m2/repository

```

I updated:
1. Ubuntu to eoan (because Cosmic has moved to old-releases)
2. Java to 8.0.232.fx-zulu (because 8.0.202-zulu has vanished)
3. Kotlin to 1.4.0 (just... uh, because), and
4. kscript to 2.9.3 (because I assumed the latest would have a fix for the main issue)

... and the problem is fixed for me.

Maybe you could update? Your container is the first hit I get in Google.

**Comment by serandel** [comment]
Updated to kscript 2.9.3 and Kotlin 1.4.10. Sorry for the wait!

Please, check that it works for you.

Also, next time a pull request would be very welcome. ;)
